### ISSUE TITLE
3DS Link error

### ISSUE THREAD

**Issue by Andyta2016** [suloku/BW_tool#6]
The app has a glitch with the 3DS link editor.
The items aren't the selected in the options
![sin titulo](https://user-images.githubusercontent.com/22484314/34329812-b0d44090-e8dc-11e7-9c45-4556cece2d1f.png)
The master ball must be a Red shard, every item is wrong and the quantity too

**Comment by suloku** [comment]
Fixed.
https://github.com/suloku/BW_tool/releases/tag/20211313_21124
